# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.TextField(max_length=10000)),
                ('incident_level', models.CharField(choices=[('1', 'Low'), ('2', 'Moderate'), ('3', 'high')], max_length=1)),
                ('location', models.CharField(max_length=50)),
                ('method', models.TextField(max_length=1000)),
                ('date', models.DateField()),
                ('notes', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Transgender')], max_length=1)),
                ('race', models.CharField(choices=[('1', 'African American'), ('2', 'Spanish/Latin'), ('3', 'White'), ('4', 'African'), ('5', 'European'), ('6', 'Aboriginal')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
