# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='date',
        ),
        migrations.AddField(
            model_name='detail',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
