# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20170816_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.ManyToManyField(to='students.Detail')),
                ('score', models.ManyToManyField(to='students.Score')),
            ],
        ),
    ]
